### ISSUE TITLE
[idp] Loop of redirection when I try to reset my password

### ISSUE THREAD

**Issue by ITPrism** [joomla/joomla-websites#1573] opened 2021-01-07 17:20 UTC
I was signed to the community websites via the identity portal.
I left the site by clicking on the Logout link.

Now, I am trying to reset my password.
When I click on the link "Forgot password" occurs redirect loop.

![Screenshot2](https://user-images.githubusercontent.com/1272206/103923006-3e890280-511d-11eb-99a1-0b92a2ed95b8.png)
![Screenshot3](https://user-images.githubusercontent.com/1272206/103923015-40eb5c80-511d-11eb-90a2-62f23a33684b.png)

**Comment by roland-d** [comment] 2021-01-23 20:07
@ITPrism Thank you for the report however I cannot reproduce it by clicking on the `Forgot Password` link. What I did was:

1. Click login on the volunteer portal
2. Logged-in
3. Click logout on the volunteer portal
4. Go to the identity.joomla.org site
5. Click login
6. Click Reset Password
7. I see the reset password page

Can you check if you can still reproduce it?

**Comment by ITPrism** [comment] 2021-01-23 20:46
OK. Let me check.

**Comment by ITPrism** [comment] 2021-01-23 22:05
1. The problem still occurs. Login to [volunteers portal](https://volunteers.joomla.org/).
2. Now go to the [community portal ](https://community.joomla.org/) and login there.
3. Go to [volunteers portal](https://volunteers.joomla.org/) and sign out yourself.
4. Go to login page and click on Forgot Password.

![Screenshot](https://user-images.githubusercontent.com/1272206/105615261-e4a06200-5dd7-11eb-970d-c569c7eaff7f.png)

**Comment by roland-d** [comment] 2021-01-24 12:38
Hello,

So I tried your steps but I still get the forgot password page. I wonder why the community portal is also here because this site is not even connected to the identity portal nor has any relation to it at this point.

Can you tell me what your IP address is? I can check the logs if I see something odd.

**Comment by roland-d** [comment] 2021-01-24 12:39
@conconnl Can you try and see if you can reproduce this issue?

**Comment by conconnl** [comment] 2021-01-24 12:54
Done, I did the exact steps as described by the user in Firefox Private Mode to make sure all login copies do not interfere. 
I wasn’t able to reproduce the issue.

**Comment by ITPrism** [comment] 2021-01-24 14:28
Hi,
OK I am going to try again.

**Comment by ITPrism** [comment] 2021-01-24 14:33
Do you still need my IP address? If you  would like to check the logs for my IP, could you give me an email where I will be able to send my IP address?

**Comment by ITPrism** [comment] 2021-01-24 14:37
I tried again. Now, I cannot open the page where I will be able to change the password. When I click on the link "Forgot password" the system redirects me back to the login page of "Joomla! Identity Portal".

**Comment by roland-d** [comment] 2021-01-24 14:49
@ITPrism I no longer need your IP address and with the new instructions of Wilco I can also reproduce the error and have seen the logfile. I am looking into it.

**Comment by roland-d** [comment] 2021-01-24 15:18
So I found the issue being that the `/login` link is only available for guest users (non logged-in) and the `/login/reset` was public. In this case you are not given access because the `/login` is not allowed and it would redirect back to `/login/reset`. This caused the redirect issue. 

To reproduce was even easier. Just login to the Identity portal and then try to go to `/login/reset`, it would show as well. The reset has been set to guest as well and that solved it.

There is no use to reset a password from that screen when you are logged-in.

**Comment by conconnl** [comment] 2021-02-13 22:02
Closing because it is fixed

**Closed by conconnl** 2021-02-13 22:02 UTC
Labels: Identity Site
