### ISSUE TITLE
[downloads] Joomla! Update on localhost server [Windows] - the archive is corrupt, truncated or archive parts are missing

### ISSUE THREAD

**Issue by trzepiz** [joomla/joomla-websites#742] opened 2016-11-05 14:21 UTC
After change Joomla! download site I have problem with all localhost servers and Joomla! Update Component. I use JAMP server but I test also XAMPP (Windows 10)

Update from 3.6.2 -> 3.6.4
**"the archive is corrupt, truncated or archive parts are missing"**

When i removed `format=zip&amp;jcompat=my.zip` from update URL - everything works fine.
Video: https://youtu.be/KNCWjLXGqLQ

**Comment by mbabker** [comment] 2016-11-05 14:48
This isn't an issue with the downloads site specifically.  If I remember what Nic said correctly, older Joomla versions required that the download URL defined in the update XMLs ended with a proper file extension (hence the jcompat segment).  The `https://downloads.joomla.org/cms/joomla3/3-6-4/joomla_3-6-4-stable-update_package-zip?format=zip&jcompat=my.zip` URL does correctly download the package and for XML compliance the ampersand is encoded in the value.

I would suggest if your system is not properly decoding the ampersand before sending the request to get the file, there is a local system configuration issue, or lesser chance a bug in Joomla core.

**Comment by wojsmol** [comment] 2016-11-06 19:21
I confirm the problem reported by @trzepiz. 
The problem occurs regardless of whether the `&amp;` is decoded correctly or not, and is specific for the Windows OS.

**Comment by mbabker** [comment] 2016-11-06 19:24
And if you remove the format segment of the URL so it doesn't require the ampersand?

I highly doubt we've got a Windows specific issue for one website in our code.  The URLs loaded in the XML are 100% valid.  Why this process is failing is something I can't debug, I stopped using Windows years ago.

**Comment by ot2sen** [comment] 2016-11-06 19:29
Tested on AMPPS on windows and got the same issue updating from 3.6.2 to
3.6.4
Has been able to update local sites with old urls until the change

**Comment by noras666** [comment] 2016-11-06 19:32
The problem is evidently in the windows.

In the url we &amp; it is of course valid.
Windows (I think) tries again encode &, which is formed in the url de facto &amp;amp; and an error occurs.

If you upgrade J! I tested that if we remove some of the parameters from the url so that & not performed. Everything works properly. I do not know when the second parameter has been added to the link in the xml file. This problem could simply not exist, because there was no second parameter in the url.

**Comment by mbabker** [comment] 2016-11-06 19:34
So back to what I said before.  This isn't an issue with the downloads site.  At best, this might be a bug in Joomla itself and debugging should be taken to the code repo to figure out what the deal is.

I'm closing this as not a bug here.  If somehow someone can isolate the issue specifically to the site (as we said in our announcement, we're using [Akeeba Release System](https://github.com/akeeba/release-system) and the download part of the code isn't one of the places we've touched), I'll be glad to look into it again, but at this time I don't see an issue specific to this platform requiring us to do something.

**Closed by mbabker** 2016-11-06 19:34 UTC
Labels: Downloads

**Comment by ot2sen** [comment] 2016-11-06 19:50
Could it be the question mark considered a reserved character on windows?

**Comment by mbabker** [comment] 2016-11-06 19:58
I doubt that otherwise a lot of code would fail on the Windows platform trying to make HTTP requests to anywhere using query strings in URLs.

**Comment by wojsmol** [comment] 2016-11-06 20:31
@ot2sen is right - it is forbidden in file names on Windows. In the joomla_update.php log you can see that the file name contains a query string. I attach the log below:

```
#Fields: datetime	priority clientip	category	message
2016-11-06T20:11:57+00:00	INFO 127.0.0.1	update	Update started by user Super User (410). Old version is 3.6.2.
2016-11-06T20:11:58+00:00	INFO 127.0.0.1	update	Downloading update file from https://downloads.joomla.org/cms/joomla3/3-6-4/joomla_3-6-4-stable-update_package-zip?format=zip&jcompat=my.zip.
2016-11-06T20:12:06+00:00	INFO 127.0.0.1	update	File joomla_3-6-4-stable-update_package-zip?format=zip&jcompat=my.zip successfully downloaded.
2016-11-06T20:12:07+00:00	INFO 127.0.0.1	update	Starting installation of new version.
```

**Comment by mbabker** [comment] 2016-11-06 20:46
OK, so that's going to be a bug in the CMS then as it'll need to be "smart" enough to not include the query string in the downloaded file name.

As for changing the update XMLs, if we can verify that older Joomla releases will work correctly with just `https://downloads.joomla.org/cms/joomla3/3-6-4/joomla_3-6-4-stable-update_package-zip` as the URL we can change it (and this goes back to 1.6.0 unfortunately).  But, if the code does do validation and requires the URL to end in a proper file extension then the URLs will have to stay as they are to ensure users on older versions are able to update as well as those on current versions.
