### ISSUE TITLE
[forum.joomla.org] 

### ISSUE THREAD

**Issue by MarkRS-UK** [joomla/joomla-websites#1322] opened 2019-05-01 13:42 UTC
The (forum) website doesn't like me?

I got a notification of a reply to a message I put on the forum recently. so I went to there and tried to reply to the reply. The website asked me to log in, but then wouldn't accept my password so I clicked the "I've forgotten" link. I received the resulting email, clicked the activation link and tried to log in with the new password, and it won't accept it.

I've re-clicked the activation link, just in case, and it tells me the account is already activated...
Can you help please. The account username is MarkRS

**Comment by MarkRS-UK** [comment] 2019-05-02 12:46
Ok, further information on this.
It appears that the website won't allow me to log in unless I check the "Remember Me" box.  Shurely shome mishtake?

**Comment by pe7er** [comment] 2019-05-03 07:58
I've checked your account and apparently you were last active at 02 May 2019.
So you are able to login now, but only when you choose "Remeber Me"? 

What browser are you using?
Could you please check it with another browser?

**Comment by MarkRS-UK** [comment] 2019-05-03 08:15
Thanks for your reply.

Yes, you're correct that I can log in, but only with "Remember Me" checked.
This is with Chrome. (under Fedora 29).
Firefox doesn't seem to have the problem.
After testing FF I went back to try Chrome again, it still needs the checkbox checked.

**Comment by pe7er** [comment] 2019-05-07 11:10
Sorry, I cannot reproduce your problem. I've tested it on Debian 9.9 with Chrome 74.0.3729.131, Chromium 73.0.3683.75 and FireFox 60.6.1. It looks like a problem with your browser at your end.

I'm gonna close this issue. If you have additional information to reproduce this error, feel free to re-open this issue.

**Closed** 2019-05-07 11:10 UTC
Labels: Forum
