### ISSUE TITLE
[jorg] 404 Links

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#318] opened 2016-04-24 18:49 UTC
A few 404 Links on joomla.org

- Source: https://www.joomla.org/announcements/release-news/5655-joomla-3-5-1-released.html
- Broken (404): https://www.joomla.org/volunteers.joomla.org/working-groups/production-leadership-team
- New: https://volunteers.joomla.org/working-groups/production-leadership-team

###### next
- Source: https://www.joomla.org/3/sk/
- Broken (404): /https://www.joomla.org/announcements/release-news/5654-joomla-3-5-is-here.html
- New: https://www.joomla.org/announcements/release-news/5654-joomla-3-5-is-here.html
- Note the `/` bevor https ;)

###### next
- Source: https://www.joomla.org/about-joomla/create-and-share.html
- Broken (404): http://community.joomla.org/translation-teams-list.html
- New (maybe): http://community.joomla.org/translations/joomla-3-translations.html
###### next
- Source: https://www.joomla.org/about-joomla/honor-roll.html
- Broken (404): http://www.joomladayboston.com
- New: `bad hoster / no DNS`

###### next
- Source: https://www.joomla.org/about-joomla/honor-roll.html
- Broken (404): http://www.ratlaw.co.uk
- New: `bad hoster / no DNS`

###### next
- Source: https://www.joomla.org/about-joomla/honor-roll.html
- Broken (404): http://trijnie.com/
- New: `bad hoster / no DNS`

###### next
- Source:
- Broken (404): https://www.joomla.org/joomlacode.org/gf/project/joomla/frs/?action=FrsReleaseView&release_id=115
- New: http://joomlacode.org/gf/project/joomla/frs/?action=FrsReleaseView&release_id=115

###### next
- Source: https://www.joomla.org/about-joomla/honor-roll.html
- Broken (404): http://www.electricjet.com
- New: `bad hoster / no DNS`

###### next
- Source: https://www.joomla.org/announcements/release-news/5645-joomla-3-5-beta-2-released-2.html
- Broken (404): https://github.com/joomla/joomla-cms/pull/8808)
- New: https://github.com/joomla/joomla-cms/pull/8808

**Comment by brianteeman** [comment] 2016-04-24 18:52
I dont get a 404 on the last one - it is successfully redirected from http
to https

On 24 April 2016 at 19:49, zero-24 <notifications@github.com> wrote:

> A few 404 Links on joomla.org
>
>    - Source:
>    https://www.joomla.org/announcements/release-news/5655-joomla-3-5-1-released.html
>    - Broken (404):
>    https://www.joomla.org/volunteers.joomla.org/working-groups/production-leadership-team
>    -
>
>    New:
>    https://volunteers.joomla.org/working-groups/production-leadership-team
>    -
>
>    Source: https://www.joomla.org/3/sk/
>    - Broken (404): /
>    https://www.joomla.org/announcements/release-news/5654-joomla-3-5-is-here.html
>    - New:
>    https://www.joomla.org/announcements/release-news/5654-joomla-3-5-is-here.html
>    -
>
>    Note the / bevor https ;)
>    -
>
>    Source: https://www.joomla.org/about-joomla/create-and-share.html
>    - Broken (404): http://community.joomla.org/translation-teams-list.html
>    -
>
>    New (maybe):
>    http://community.joomla.org/translations/joomla-3-translations.html
>    -
>
>    Source: https://www.joomla.org/about-joomla/honor-roll.html
>    - Broken (404): http://www.joomladayboston.com
>    -
>
>    New: bad hoster / no DNS
>    -
>
>    Source: https://www.joomla.org/about-joomla/honor-roll.html
>    - Broken (404): http://www.ratlaw.co.uk
>    -
>
>    New: bad hoster / no DNS
>    -
>
>    Source: https://www.joomla.org/about-joomla/honor-roll.html
>    - Broken (404): http://trijnie.com/
>    -
>
>    New: bad hoster / no DNS
>    -
>
>    Source:
>    - Broken (404):
>    https://www.joomla.org/joomlacode.org/gf/project/joomla/frs/?action=FrsReleaseView&release_id=115
>    -
>
>    New:
>    http://joomlacode.org/gf/project/joomla/frs/?action=FrsReleaseView&release_id=115
>    -
>
>    Source: https://www.joomla.org/about-joomla/honor-roll.html
>    - Broken (404): http://www.electricjet.com
>    -
>
>    New: bad hoster / no DNS
>    -
>
>    Source:
>    https://www.joomla.org/announcements/release-news/5645-joomla-3-5-beta-2-released-2.html
>    - Broken (404): joomla/joomla-cms#8808
>    <https://github.com/joomla/joomla-cms/pull/8808>)
>    - New: joomla/joomla-cms#8808
>    <https://github.com/joomla/joomla-cms/pull/8808>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/318>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment] 2016-04-24 18:55
This is because on the site we have `joomla/joomla-cms#8808)` as link (notice the `)`) github catch the link and automagic correct it here ;)

**Comment by brianteeman** [comment] 2016-04-24 19:03
ah didnt spot the )

On 24 April 2016 at 19:55, zero-24 <notifications@github.com> wrote:

> This is because on the site we have joomla/joomla-cms#8808) as link
> (notice the )) github catch the link and automagic correct it here ;)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/318#issuecomment-214022690>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Sandra97** [comment] 2016-04-24 19:30
@zero-24 Thanks for the report!
Nearly all corrected except the 1st one, as I can't reproduce the error, the link on the announcement works fine for me (or has been corrected by someone else).
Closing this issue. Re-open it if needed

**Closed by Sandra97** 2016-04-24 19:30 UTC
Labels: .org, content, wrong link
