### ISSUE TITLE
CSP errors on 'docs.joomla.org' 

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#1202] opened 2018-08-08 08:18 UTC
Hi,

Rochen (Jeremy) sent me a ticket about CSP Violations on docs.joomla.org.

> We're now seeing a large surge of these email notifications, but for 'docs.joomla.org' 

[root@joomla-misc ~]# exim -Mvb 1fn00U-005iZp-4T
1fn00U-005iZp-4T-D
{
"csp-report": {
"document-uri": "https://docs.joomla.org/index.php?title=Special:UserLogin&returnto=J3.x:Installing+Joomla",
"referrer": "https://docs.joomla.org/index.php?title=Special:UserLogin&returnto=J3.x:Installing+Joomla",
"violated-directive": "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.google-analytics.com https://*.googletagmanager.com https://*.google.com https://*.joomla.org https://*.pingdom.net https://*.doubleclick.net https://*.addthis.com https://*.carbonads.com https://*.carbonads.net https://*.addthisedge.com https://*.facebook.com https://widgets.pinterest.com https://freegeoip.net https://www.googleapis.com https://commons.wikimedia.org",
"effective-directive": "script-src",
"original-policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.google-analytics.com https://*.googletagmanager.com https://*.google.com https://*.joomla.org https://*.pingdom.net https://*.doubleclick.net https://*.addthis.com https://*.carbonads.com https://*.carbonads.net https://*.addthisedge.com https://*.facebook.com https://widgets.pinterest.com https://freegeoip.net https://www.googleapis.com https://commons.wikimedia.org; style-src 'self' 'unsafe-inline' https://www.google.com; connect-src 'self' https://*.doubleclick.net https://*.google-analytics.com https://google-analytics.com https://*.addthis.com; frame-src 'self' https://*.google.com https://www.googletagmanager.com https://*.addthis.com https://*.youtube.com https://*.vimeo.com; img-src 'self' data: https://*.joomla.org https://*.buysellads.net https://ad.doubleclick.net https://www.google-analytics.com https://*.doubleclick.net https://*.convertro.com https://*.google.com https://www.googleapis.com https://*.gstatic.com https://www.googletagmanager.com https://*.travis-ci.org https://*.servedby-buysellads.com https://*.addthis.com https://*.google-analytics.com https://*.ytimg.com https://upload.wikimedia.org https://www.mediawiki.org; report-uri https://community.joomla.org/scripts/csp-reporter.php?source=docs.joomla.org",
"blocked-uri": "http://freegeoip.net",
"status-code": 0
}
}

UserAgent: Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

Violated Directive: script-src

Blocked Domain: freegeoip.net

Blocked Uri: http://freegeoip.net

ReportSource: docs.joomla.org

CC:  @zero-24

**Comment by Sandra97** [comment] 2018-08-08 08:41
Tom and Tobias are already looking at that.

**Comment by Sandra97** [comment] 2018-08-08 08:43
Note that GEOIP has been turned off, and there is no suitable replacement without paying for the service.

**Comment by brianteeman** [comment] 2018-08-08 09:48
https://github.com/apilayer/freegeoip#readme

**Comment by Hutchy68** [comment] 2018-08-08 12:53
Thanks, but the free account allows for only 10000 lookups per month. We won’t even make it a week before hitting the threshold.

**Comment by brianteeman** [comment] 2018-08-08 13:02
I was sharing it for the information ;)

And no reason not to approach them for a free account in exchange for a logo. Other projects get paid to use peoples products - at a minimum we should get them for free

**Comment by zero-24** [comment] 2018-08-08 19:00
The issue was fixed already this night buy stopping the reports and later by Tom on removing the call. As I can't update the ticket with rochen please report that back to them.

**Comment by anibalsanchez** [comment] 2018-08-08 19:15
I've already closed the ticket and linked it to this ticket.

**Comment by zero-24** [comment] 2018-08-08 19:55
Please close the issue than too as the issue is fixed. Thanks @anibalsanchez

**Closed** 2018-08-08 20:01 UTC
Labels: Documentation
