### ISSUE TITLE
[idp] identity site captcha fails

### ISSUE THREAD

**Issue by rotech1** [joomla/joomla-websites#1452] opened 2020-06-01 22:26 UTC
Pleas### Steps to reproduce the issue
visit  https://identity.joomla.org/register and attempt to register

### Expected result
registration

### Actual result

Error
Empty solution not allowed.

Invalid field: Captcha

### System information (as much as possible)

latest chrome browser Version 83.0.4103.61 (Official Build) (64-bit)

### Additional comments

no captcha is visible on the form!!e describe the problem or your issue

**Comment by conconnl** [comment] 2020-06-14 13:30
@rotech1 I checked your issue.
Captcha is not shown because it's the invisible version.
It's available in the code and form.
I haven't been able to reproduce it.

Possibly it was already fixed in the mean time.
Would you be able to try it again, reopen the issue and provide a screenshot if it still happens?

**Closed by conconnl** 2020-06-14 13:30 UTC
Labels: Identity Site
