### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by SleepTheGod** [joomla/joomla-websites#1853] opened 2022-12-19 07:07 UTC
https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode

Symfony\Component\Cache\Exception\InvalidArgumentException
Cache key "wiki.page-help{major}{minor}_{keyref}.lang-{langcode" contains reserved characters "{}()/\@:".

<html>
<body>
<table class="line-wrap"><tbody><tr><td class="line-number" value="1"></td><td class="line-content"><span class="html-doctype">&lt;!DOCTYPE html&gt;</span></td></tr><tr><td class="line-number" value="2"></td><td class="line-content"><span class="html-tag">&lt;html <span class="html-attribute-name">lang</span>="<span class="html-attribute-value">en</span>" <span class="html-attribute-name">dir</span>="<span class="html-attribute-value">ltr</span>"&gt;</span></td></tr><tr><td class="line-number" value="3"></td><td class="line-content">    <span class="html-tag">&lt;head&gt;</span></td></tr><tr><td class="line-number" value="4"></td><td class="line-content">        <span class="html-tag">&lt;meta <span class="html-attribute-name">name</span>="<span class="html-attribute-value">viewport</span>" <span class="html-attribute-name">content</span>="<span class="html-attribute-value">width=device-width, initial-scale=1.0</span>" /&gt;</span></td></tr><tr><td class="line-number" value="5"></td><td class="line-content">        <span class="html-tag">&lt;title&gt;</span>Joomla! Help Screens<span class="html-tag">&lt;/title&gt;</span></td></tr><tr><td class="line-number" value="6"></td><td class="line-content">        <span class="html-tag">&lt;link <span class="html-attribute-name">rel</span>="<span class="html-attribute-value">stylesheet</span>" <span class="html-attribute-name">href</span>="<a class="html-attribute-value html-resource-link" target="_blank" href="https://help.joomla.org/media/css/help.css?id=85e1d7fecdaa4c10d305" rel="noreferrer noopener">/media/css/help.css?id=85e1d7fecdaa4c10d305</a>" <span class="html-attribute-name">crossorigin</span>="<span class="html-attribute-value">anonymous</span>" <span class="html-attribute-name">integrity</span>="<span class="html-attribute-value">sha384-2iCsSxw2kqihbdYvpphwUDNAwZVkc/pkKLOIkMoMiDQCn9rkli8h5oMDTZloSN3r</span>"&gt;</span></td></tr><tr><td class="line-number" value="7"></td><td class="line-content">            <span class="html-tag">&lt;/head&gt;</span></td></tr><tr><td class="line-number" value="8"></td><td class="line-content">    <span class="html-tag">&lt;body&gt;</span></td></tr><tr><td class="line-number" value="9"></td><td class="line-content">        <span class="html-tag">&lt;a <span class="html-attribute-name">name</span>="<span class="html-attribute-value">Top</span>" <span class="html-attribute-name">id</span>="<span class="html-attribute-value">Top</span>"&gt;</span><span class="html-tag">&lt;/a&gt;</span></td></tr><tr><td class="line-number" value="10"></td><td class="line-content">            <span class="html-tag">&lt;h1&gt;</span>Symfony\Component\Cache\Exception\InvalidArgumentException<span class="html-tag">&lt;/h1&gt;</span></td></tr><tr><td class="line-number" value="11"></td><td class="line-content">    <span class="html-tag">&lt;p&gt;</span>Cache key &amp;quot;wiki.page-help{major}{minor}_{keyref}.lang-{langcode&amp;quot; contains reserved characters &amp;quot;{}()/\@:&amp;quot;.<span class="html-tag">&lt;/p&gt;</span></td></tr><tr><td class="line-number" value="12"></td><td class="line-content">        <span class="html-tag">&lt;div <span class="html-attribute-name">id</span>="<span class="html-attribute-value">footer-wrapper</span>"&gt;</span></td></tr><tr><td class="line-number" value="13"></td><td class="line-content">                            <span class="html-tag">&lt;div <span class="html-attribute-name">id</span>="<span class="html-attribute-value">license</span>"&gt;</span>License: <span class="html-tag">&lt;a <span class="html-attribute-name">href</span>="<a class="html-attribute-value html-external-link" target="_blank" href="https://docs.joomla.org/JEDL" rel="noreferrer noopener">https://docs.joomla.org/JEDL</a>" <span class="html-attribute-name">target</span>="<span class="html-attribute-value">_blank</span>"&gt;</span>Joomla! Electronic Documentation License<span class="html-tag">&lt;/a&gt;</span><span class="html-tag">&lt;/div&gt;</span></td></tr><tr><td class="line-number" value="14"></td><td class="line-content">                <span class="html-tag">&lt;div <span class="html-attribute-name">id</span>="<span class="html-attribute-value">copyright</span>"&gt;</span>Copyright &amp;copy; 2022 <span class="html-tag">&lt;a <span class="html-attribute-name">href</span>="<a class="html-attribute-value html-external-link" target="_blank" href="https://www.opensourcematters.org/" rel="noreferrer noopener">https://www.opensourcematters.org</a>" <span class="html-attribute-name">target</span>="<span class="html-attribute-value">_blank</span>"&gt;</span>Open Source Matters, Inc.<span class="html-tag">&lt;/a&gt;</span> All rights reserved.<span class="html-tag">&lt;/div&gt;</span></td></tr><tr><td class="line-number" value="15"></td><td class="line-content">                <span class="html-tag">&lt;div <span class="html-attribute-name">id</span>="<span class="html-attribute-value">report-an-issue</span>"&gt;</span><span class="html-tag">&lt;a <span class="html-attribute-name">href</span>="<a class="html-attribute-value html-external-link" target="_blank" href="https://github.com/joomla/joomla-websites/issues/new?title=[jhelp]%20&amp;body=Please%20describe%20the%20problem%20or%20your%20issue" rel="noreferrer noopener">https://github.com/joomla/joomla-websites/issues/new?title=[jhelp]%20&amp;amp;body=Please%20describe%20the%20problem%20or%20your%20issue</a>" <span class="html-attribute-name">target</span>="<span class="html-attribute-value">_blank</span>"&gt;</span>Report an Issue<span class="html-tag">&lt;/a&gt;</span> with the help screens<span class="html-tag">&lt;/div&gt;</span></td></tr><tr><td class="line-number" value="16"></td><td class="line-content">                    <span class="html-tag">&lt;/div&gt;</span></td></tr><tr><td class="line-number" value="17"></td><td class="line-content">        <span class="html-tag">&lt;hr/&gt;</span></td></tr><tr><td class="line-number" value="18"></td><td class="line-content">        <span class="html-tag">&lt;a <span class="html-attribute-name">href</span>="<a class="html-attribute-value html-external-link" target="_blank" href="https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&amp;lang={langcode#Top" rel="noreferrer noopener">https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&amp;amp;lang={langcode#Top</a>"&gt;</span>Top<span class="html-tag">&lt;/a&gt;</span></td></tr><tr><td class="line-number" value="19"></td><td class="line-content">            <span class="html-tag">&lt;/body&gt;</span></td></tr><tr><td class="line-number" value="20"></td><td class="line-content"><span class="html-tag">&lt;/html&gt;</span></td></tr><tr><td class="line-number" value="21" style="font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"></td><br class="Apple-interchange-newline">
</body>
</html><!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Joomla! Help Screens</title>
        <link rel="stylesheet" href="[/media/css/help.css?id=85e1d7fecdaa4c10d305](https://help.joomla.org/media/css/help.css?id=85e1d7fecdaa4c10d305)" crossorigin="anonymous" integrity="sha384-2iCsSxw2kqihbdYvpphwUDNAwZVkc/pkKLOIkMoMiDQCn9rkli8h5oMDTZloSN3r">
            </head>
    <body>
        <a name="Top" id="Top"></a>
            <h1>Symfony\Component\Cache\Exception\InvalidArgumentException</h1>
    <p>Cache key &quot;wiki.page-help{major}{minor}_{keyref}.lang-{langcode&quot; contains reserved characters &quot;{}()/\@:&quot;.</p>
        <div id="footer-wrapper">
                            <div id="license">License: <a href="https://docs.joomla.org/JEDL" target="_blank">Joomla! Electronic Documentation License</a></div>
                <div id="copyright">Copyright &copy; 2022 <a href="https://www.opensourcematters.org/" target="_blank">Open Source Matters, Inc.</a> All rights reserved.</div>
                <div id="report-an-issue"><a href="[https://github.com/joomla/joomla-websites/issues/new?title=[jhelp]%20&amp;body=Please%20describe%20the%20problem%20or%20your%20issue](https://github.com/joomla/joomla-websites/issues/new?title=[jhelp]%20&body=Please%20describe%20the%20problem%20or%20your%20issue)" target="_blank">Report an Issue</a> with the help screens</div>
                    </div>
        <hr/>
        <a href="[https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&amp;lang={langcode#Top](https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode#Top)">Top</a>
            </body>
</html>

**Comment by dicson2** [comment] 2023-01-26 18:09
Got the same error, as follows: 

Home Dashboard => Content Dashboard => Content Settings => Articles: Fields
? Help => Fields description => Column Headers => Type. 
Learn more => 

[Result:] 

Symfony\Component\Cache\Exception\InvalidArgumentException
Cache key "wiki.page-j3.x_adding_custom_fields.lang-calendar_field/en" contains reserved characters "{}()/\@:".

**Comment by HLeithner** [comment] 2023-03-03 10:52
This is a duplicate of #1828
I'm closing this.

**Closed by HLeithner** 2023-03-03 10:52 UTC
