### ISSUE TITLE
[jlaunch] Joomla.com Update mails contain confusing url

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1841] opened 2022-11-29 11:41 UTC
See screenshot:

<img width="842" alt="grafik" src="https://user-images.githubusercontent.com/828371/204519856-04b2e778-f7b9-42e9-9725-ab621700923a.png">

**Comment by HLeithner** [comment] 2022-11-29 12:49
@dmitriy-cloudaccess we have some issues reported for joomla.com in this repo, are you the right person which can help on this topics? https://github.com/joomla/joomla-websites/issues?q=is%3Aissue+is%3Aopen+joomla.com

**Comment by Pawel-Panek** [comment] 2022-12-02 20:14
Please tag @Pawel-Panek or @dereksca for launch.joomla.org provisioning issues.

@coolcat-creations can you edit the tile to have `[jlaunch]` in front?

The problem with this notification has been discussed widely here: https://github.com/joomla/joomla-cms/issues/35600 .

**Comment by Pawel-Panek** [comment] 2022-12-02 20:15
@coolcat-creations I mean for all those issues related to LJO posted recently by you. The title should start with [jlaunch] so we can easily filter them. Thank you.

**Comment by HLeithner** [comment] 2022-12-03 08:53
@Pawel-Panek thanks for the info, I added jlaunch to all of the issue I could found and tagged you in an old one.
If you or a colleague thinks a issue can be closed please tag me or @pe7er

**Comment by brianteeman** [comment] 2022-12-06 08:48
This ip6 issue has been ongoing for several years

**Comment by Pawel-Panek** [comment] 2023-01-06 10:12
That's not related to the IPv6 access. The thread regarding this notification has been started in here: https://github.com/joomla/joomla-cms/issues/35600

@coolcat-creations I think this one can be closed as the issue is about Joomla CMS and not the launch site.

**Comment by HLeithner** [comment] 2023-01-06 12:37
I reopened the relevant PR at the cms https://github.com/joomla/joomla-cms/issues/35600 and close this one, thanks @Pawel-Panek

**Comment by HLeithner** [comment] 2023-01-06 12:38
for the meantime @Pawel-Panek could you maybe add the live_site parameter, would this work for you?

**Closed by HLeithner** 2023-01-06 12:37 UTC

**Comment by brianteeman** [comment] 2023-01-06 13:29
commenting here as I am unable to comment on the other issue.

this is a server configuration issue and not a joomla issue

**Comment by HLeithner** [comment] 2023-01-06 13:36
more or less true, but we have the same problem in joomla 4 with cli scripts and as mentioned could be fixed by setting live_site parameter

**Comment by brianteeman** [comment] 2023-01-06 13:53
>  could be fixed by setting live_site parameter

**should** be fixed by the borken host

**Comment by HLeithner** [comment] 2023-01-06 14:17
that's the reason why I ask pawel if they can fix it.

**Comment by brianteeman** [comment] 2023-01-06 14:20
if they can't then its just another reason not to use them and to find a better provider

**Comment by brianteeman** [comment] 2023-01-11 08:49
@Pawel-Panek  Why is this only an issue for cloudaccess and not for any other host?

**Comment by HLeithner** [comment] 2023-01-11 09:00
It's an issue for any other host, that allows to access the website by IP and has nothing explicit to do with cloudaccess it self only with the configuration.

If you open https://[2607:1b00:93b2:e42c::2e88]/ you will see the website. Since I don't have IPv6 on this connection I can't check.

I'm not sure if you can use an arbitrary domain, can you confirm that this not possible? if it's possible you have a bigger problem.

**Comment by HLeithner** [comment] 2023-01-11 09:16
> Starting with the fact that you can not get an ssl certificate for an ip address

fact? sorry that's wrong it's possible to get a ssl certificate for an IP

**Comment by brianteeman** [comment] 2023-01-11 09:24
fact was used as an expression (ot)

only from limited providers and only by the person that owns the ip address
