### ISSUE TITLE
[jcm] should this be published?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1085] opened 2017-11-29 20:28 UTC
https://magazine.joomla.org/all/itemlist/category/12-submitted-articles-bucket

**Comment by brianteeman** [comment] 2017-12-04 17:29
And i am assuming that this shouldnt have been published either which has just triggered all the twitter bots
https://magazine.joomla.org/all/item/3291-the-december-issue

**Comment by brianteeman** [comment] 2017-12-04 17:53
In case you didnt realise what this means it is that all the content in the submissions bucket is now visible to the internet - including stuff that is quite old and probably best not to be published

**Comment by JacquesR** [comment] 2017-12-04 18:18
Thanks for the alert. Someone keeps on fiddling with the access level of the Submissions bucket, and I have no idea who. I now again had to change at back from Public, same as 5 days ago.

Each time that happens, the feed gets picked up by tweets and google feedburner. The puzzle is that only a very few has back-end access and none of them is a likely culprit. (specially since I mentioned the issue 5 days ago)

It's frustrating.

**Comment by brianteeman** [comment] 2017-12-04 18:25
Sounds like you must have a hacker them. That's a really serious issue if someone is able to login and change acl on k2

**Comment by JacquesR** [comment] 2017-12-04 18:44
Unless a hacker is just out to annoy us, it seems unlikely that hacking is the cause of this. I'll chat to those who most recently had back-end access to try and figure this out.

**Comment by Sandra97** [comment] 2018-04-17 09:37
Seems to be fine now.
I'm closing this issue. 
Re-open if it happens again.

**Closed by Sandra97** 2018-04-17 09:37 UTC
Labels: JCM
