### ISSUE TITLE
Hamburger Menu is not closing after it is opened.

### ISSUE THREAD

**Issue by naveengitboi** [joomla/joomla-websites#1872] opened 2023-02-22 19:34 UTC
### Steps to reproduce the issue

I couldn't find the code, because im new to php, xml. (Somehow I learnt basics of php to solve this, but couldn't)
But there is something like **collapse-nav**. Might there is some error which causing this issue.

### Expected result

The Expected result is to close when user clicked on menu if it opened,  vice-versa.

### Actual result

Now when a user clicked menu, its showing data as expected but unable to close that even after multiple clicks.

### Additional comments

![joomla](https://user-images.githubusercontent.com/110653456/220740001-7e49661a-4805-4d62-9d9f-79e882146d65.jpg)

Not an big issue though, but surly impacts the user experience.

**Comment by brianteeman** [comment] 2023-02-22 20:22
Which browser & device are you using? I am unable to replicate this

**Comment by naveengitboi** [comment] 2023-02-22 20:41
Google Chrome, (Version 110.0.5481.178 (Official Build) (64-bit)),
Windows.

**Comment by brianteeman** [comment] 2023-02-22 21:06
This is a recording of my pc using Version 110.0.5481.178 (Official Build) (64-bit) on windows 11

As you can see there is no problem at all or I am looking at the wrong thing

![hamburger](https://user-images.githubusercontent.com/1296369/220759192-ad4372c2-f630-4e4e-ab30-d6bdf8dbc2f4.gif)

**Comment by wilsonge** [comment] 2023-02-23 00:04
I can confirm it’s an issue on my iPhone. But it’s also not an issue on iOS or Android on the new j4 template. So hopefully this will be closed as a won’t fix in the next months as we migrate over to J4

**Comment by naveengitboi** [comment] 2023-02-23 08:39
https://user-images.githubusercontent.com/110653456/220858065-37a0d880-9ed0-4f06-9aa3-1e265096cc52.mp4


Android, Google chrome.

**Comment by brianteeman** [comment] 2023-02-23 09:22
Why would you expect the hamburger to collapse just because you have clicked on something that does nothing more than expand and display some menu items. The hamburger menu only collapses when you actually go somewhere. Until then you havent finished with the menu

**Comment by HLeithner** [comment] 2023-02-23 09:45
Wäre is you problem Brian?
It's perfectly fine to expect that the menu closes again when I click on the button again as in "every"? Other page too.
So please stop wasting time when George already told us that it's fixed in the upgrade. Thanks

And thanks to @naveengitboi thanks for your report it's perfectly fine and also the initial report was enough to reproduce the issue.

**Comment by brianteeman** [comment] 2023-02-23 09:55
> Wäre is you problem Brian?

Trying to understand the reported problem

**Comment by B1TSH3LL** [comment] 2023-03-04 14:03
As n Gsoc Contribution i wanted to work on this issue. Please assign this to me.

**Closed** 2023-05-20 10:42 UTC
Labels: bug
