### ISSUE TITLE
[joom.la] Short URLs not being generated

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-websites#903] opened 2017-03-26 15:56 UTC
None of the sites using the social sharing plugin are getting short URLs back, so the sharing actions have the full page URLs.

**Comment by zero-24** [comment] 2017-03-26 16:19
Did the plugin switched to HTTPS? Iirc there was a change like this?

**Comment by mbabker** [comment] 2017-03-26 16:20
Shouldn't matter because a properly configured server would redirect the request from HTTP to HTTPS.

Yes, the config is updated at least on the dev site to explicitly use HTTPS and that still is busted.

**Comment by zero-24** [comment] 2017-03-26 16:21
Thanks for checking 👍  it was just my first idea.

**Comment by Radek-Suski** [comment] 2017-03-27 11:46
The site redirects to https but AFAIR it (redirects) won't be supported by the plugin. Apparently also the token has been changed after latest update (face palm).
I am sending the new token in webmaster team

**Comment by Sandra97** [comment] 2017-03-27 12:18
Updated on jorg, repo, repo/3, all good on these ones.
Done also on /3 but it doesn't work.

**Comment by Sandra97** [comment] 2017-04-02 13:39
org, /3, repo, dev, cjo = works as expected.
Not working on VP, I told Sander.

**Comment by Sandra97** [comment] 2017-04-22 10:56
Still not working on the Volunteers Portal, @sanderpotjer Could you give a look? Thank you!

**Comment by sanderpotjer** [comment] 2017-04-23 19:32
The issue is now fixed on the Volunteers Portal. I thought the new key would be enough, but it seems there is no automatic redirect to the https version, so forced this now. Shorten links are working again.

**Closed by sanderpotjer** 2017-04-23 19:32 UTC
Labels: bug
