### ISSUE TITLE
[jshow] Can't upload image

### ISSUE THREAD

**Issue by ufuk-avcu** [joomla/joomla-websites#996] opened 2017-07-17 08:22 UTC
Hi everyone,

this is not verified by me. I got a mail from a guy, who try to add his own site to the showcase. 

> I tried to submit my site but it won’t allow me to upload an image. I’ve tried different formats and size but I keep getting an unknown error.

Best regards

**Comment by Sandra97** [comment] 2017-07-17 10:17
Sébastien is not available for the next 2 weeks, he will look at Showcase issues when he is back.

I just checked if I can reproduce. I confirm when you upload a picture, you have each time an `Unknown error`

**Comment by zero-24** [comment] 2017-07-17 10:29
Is there a special error or just `Unknown error` ? As the new mime type checks may force to check the allowed mime types in the backed.

**Comment by Sandra97** [comment] 2017-07-17 10:35
Just Error: Unknown Error, nothing else displayed.

**Comment by zero-24** [comment] 2017-07-17 10:45
hmm do you have a login for the backed? If yes can you check the com_media upload settings? And try to upload the same file using com_media? If that is working it could be something else.

**Comment by Sandra97** [comment] 2017-07-17 10:47
Nope I don't have access. Can't help with that.

**Comment by Sandra97** [comment] 2017-07-17 10:49
@alexandrelapoux @oliviernolbert Would it be possible for one of you to look at that issue?

**Comment by oliviernolbert** [comment] 2017-07-19 07:38
Hi @Sandra97 We're checking this issue.

**Comment by oliviernolbert** [comment] 2017-07-19 09:22
@Sandra97 Maybe there's no disk space left on the server? Could someone with access to server info check this?

**Comment by Sandra97** [comment] 2017-07-19 09:48
Hi @oliviernolbert 
Disk usage is ok so it's not the issue.
![cpanel - main](https://user-images.githubusercontent.com/4682328/28361162-e365bb2e-6c45-11e7-8e50-287f71357edf.png)

**Comment by oliviernolbert** [comment] 2017-07-24 09:01
Hi @Sandra97,

After several tests (not easy as we can not display errors on website), we've noticed the issue is coming from the Ajax POST call that tries to push the images on the server. Ajax GET calls work.

Can someone check if there was a configuration update or a new security rule done in the previous weeks because the code is still the same on our side for the image upload management.

Can some also check if there's no specific quota on the 'images' folder ?

Thank you.

**Comment by Sandra97** [comment] 2017-07-24 09:50
Hi @oliviernolbert 

Do you know at which date you updated to 3.7.3?
Not that uploading pictures were working fine until July 6th (last time I submitted successfully a site).

**Comment by Sandra97** [comment] 2017-07-24 10:12
It seems there's no restriction for the images folder.

There appears to be be a lot of extensions that are out of date. 
Could you please make sure everything is up to date first including the template? 
If that doesn't fix it, with a fully up to date system, we'll talk to Rochen.

**Comment by Sandra97** [comment] 2017-08-08 11:45
Uploading images work again.
I'm closing this issue.
Re-open if needed.

**Closed by Sandra97** 2017-08-08 11:45 UTC
Labels: Showcase
