### ISSUE TITLE
[joomla.org] %logintext% error

### ISSUE THREAD

**Issue by Hittitech** [joomla/joomla-websites#1881] opened 2023-04-03 15:49 UTC
while clicking on the %logintext%  it is showing 400 bad request
https://www.joomla.org/4/en/ here is the link 
![Screenshot (6)](https://user-images.githubusercontent.com/87484115/229561520-d54beb94-8106-472a-8cb9-832721eeb415.png)
![Screenshot (7)](https://user-images.githubusercontent.com/87484115/229561533-00f5de19-7363-4409-8299-3e3d768306df.png)

**Comment by chmst** [comment] 2023-04-03 17:02
confirmed

**Comment by Hittitech** [comment] 2023-04-03 18:03
> confirmed
can i work on it ?

**Comment by TLWebdesign** [comment] 2023-04-17 18:37
I've hidden it for now with some css but since this is pulled in from the CDN it should be fixed by someone that has access to that part.

**Closed** 2023-08-08 08:14 UTC
