### ISSUE TITLE
[jlaunch] Joomla.com two super users

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-websites#1837] opened 2022-11-29 10:20 UTC
When installing a joomla.com site there are two super users, as the number of super users should be limited this is not a good practice, especially when there is only one admin

**Comment by dereksca** [comment] 2022-11-30 14:46
That is as intended. That additional user is added so that the CCP features, like the login from CCP, work properly, and so that our support has access to provide help without asking for login credentials every time. We tried achieving that with a single user in the past and it created a lot of issues for our clients and ourselves.

**Comment by HLeithner** [comment] 2022-12-03 08:46
Thanks @dereksca for the feedback, I'm closing this issue.

**Closed by HLeithner** 2022-12-03 08:46 UTC
