### ISSUE TITLE
[jorg] 

### ISSUE THREAD

**Issue by simplytammy** [joomla/joomla-websites#1341] opened 2019-08-07 13:46 UTC
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
It could be useful to include an URL of evidence.
Please use a consistent title for your issue.

The dropdown main menu(top right) on https://joomla.org homepage fails to close on my mobile device. It opens on click but stays open and won't close. I think it's a bug and you should check it out.

**Comment by Sandra97** [comment] 2019-08-09 11:04
Hi, 

It's a known bug: duplicate of #1211 so I'm closing this issue.  

If you have an idea how to fix it, please don't hesitate.

**Closed by Sandra97** 2019-08-09 11:04 UTC
