### ISSUE TITLE
[jdocs] spam report

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1047] opened 2017-09-26 09:04 UTC
https://docs.joomla.org/index.php?search=kindle

**Comment by Sandra97** [comment] 2017-09-26 10:00
Thanks Brian for reporting. Page deleted.

**Comment by brianteeman** [comment] 2017-09-26 10:18
Looks like you only deleted one page - there were four

**Comment by Sandra97** [comment] 2017-09-26 10:19
The other ones were already deleted.

**Comment by Sandra97** [comment] 2017-09-26 10:20
I have to see with @Hutchy68  if there is a way to remove them from the search system too

**Comment by brianteeman** [comment] 2017-09-26 10:22
Ah I see that the content gets deleted but the title and therefore the page remains so they only have to spam in the title for it to stay - which is weird

**Comment by Hutchy68** [comment] 2017-09-26 12:31
The issue is Google! They are ignoring meta noindex, nofollow tags. Forum has a few too.

![image](https://user-images.githubusercontent.com/3527469/30860404-033d3546-a295-11e7-8ac2-ebadd89cbaac.png)

**Comment by Sandra97** [comment] 2017-09-26 12:37
I've asked Google to stop indexing them.

**Comment by brianteeman** [comment] 2017-09-26 12:48
Surely the wiki should not respond to a non existent page with anything other than  a 404

https://docs.joomla.org/Georgelovesorange

That should only be a 404.

**Comment by Hutchy68** [comment] 2017-09-26 12:54
It does send the appropriate header of 404.

![image](https://user-images.githubusercontent.com/3527469/30861147-cd2de4e8-a297-11e7-94dd-debd97498a8b.png)

It is similar to a custom Joomla 404 page.

And it also has meta robots noindex,nofollow. 

I just added another dozen or so.

**Comment by brianteeman** [comment] 2017-09-26 13:00
At least the message on screen for a Joomla 404 makes it clear that the page doesn't exist. The message on the wiki suggests the page exists but has no content yet or it is a work in progress

**Comment by Sandra97** [comment] 2017-09-26 13:03
It is clearly mentioned the page has been deleted.

**Comment by brianteeman** [comment] 2017-09-26 13:06
![screenshot_20170926-140252](https://user-images.githubusercontent.com/1296369/30861843-f1158146-a2c3-11e7-82c0-b7185b9407f1.png)

**Comment by brianteeman** [comment] 2017-09-26 13:08
On one of the deleted pages it is exactly the same.

![screenshot_20170926-140427](https://user-images.githubusercontent.com/1296369/30861931-2bb9037c-a2c4-11e7-8d8d-f15a43df1369.png)

**Comment by Sandra97** [comment] 2017-09-26 13:16
The messages I have are different from yours, but it's obviously because I'm logged in.

**Comment by Hutchy68** [comment] 2017-09-26 13:32
![image](https://user-images.githubusercontent.com/3527469/30862912-8a822784-a29d-11e7-8d01-dfa84beca5fc.png)

Better?

**Comment by brianteeman** [comment] 2017-09-26 13:52
Yes - thanks!!!

**Comment by Sandra97** [comment] 2017-10-01 10:28
Google has removed these pages (one remaining in the search results but should be removed soon), and 404 page created so I'm closing this issue.
Re-open if needed.

**Comment by brianteeman** [comment] 2017-10-01 10:31
thank you!!!

**Closed** 2017-10-01 10:31 UTC
