### ISSUE TITLE
Presentation Joomla4 with mission picture - great opportunitty for new account :)

### ISSUE THREAD

**Issue by pinochico** [joomla/joomla-websites#1669] opened 2021-09-22 13:20 UTC
https://www.joomla.org/4/#features

Wrong html code, don't exist image variant (.jpg) for other browser(safari), only webp for chrome.
Now I don't see any image - is not good info about joomla4 for others.

![Screenshot 2021-09-22 at 15 12 54](https://user-images.githubusercontent.com/395559/134350941-b33389d5-45e8-43a7-b59e-948d0d2ea277.png)
![Screenshot 2021-09-22 at 15 12 34](https://user-images.githubusercontent.com/395559/134350948-88f2a4c4-544f-4e9a-b928-0b999cf8c38c.png)
![Screenshot 2021-09-22 at 15 12 21](https://user-images.githubusercontent.com/395559/134350965-ae9f045d-9ce0-4a22-a64a-352e1b0c8dff.png)

**Comment by conconnl** [comment] 2021-09-22 16:13
I can’t reproduce see images in multiple browsers on different devices and internet connections.

**Comment by pinochico** [comment] 2021-09-22 16:20
Hi, try again pls, in html code on Safari browser (mac) I see only code for
img with URL for WEBP (look at my before post in attachment, do you see?).
Every developer knows that webp is not showing on safari and then html code
for image with webp has to be changed to image with JPG.

And I see a web site with errors.

If you need, then tomorrow on Czech Joomla Cafe I will speak with other
developers with Apple and all will create the same issues.

Thanks and Best Regards


Rudolf Baláš

web support manager
***@***.***
+420 730 517 521
Minion Interactive s. r. o. | www.minion.cz
Jiráskova 16, 466 01 Jablonec nad Nisou
+420 480 023 139, email: ***@***.*** ***@***.***>

www.minion.cz | www.tvorbaloga.cz | www.tvorbainfografiky.cz
www.facebook.com/MinionInteractive
www.twitter.com/minioncz


st 22. 9. 2021 v 18:13 odesílatel Wilco Alsemgeest ***@***.***>
napsal:

**Comment by conconnl** [comment] 2021-09-22 16:30
I just shared my result on Apple and Windows devices. I don’t see any errors.

**Comment by pinochico** [comment] 2021-09-22 16:36
ok, I think of course, because you have big sure os on apple?.
But safari is only partially supported, I have OS Mojave and Safari 13 and
I don't see webp.

Thanks
Rudolf Baláš

web support manager
***@***.***
+420 730 517 521
Minion Interactive s. r. o. | www.minion.cz
Jiráskova 16, 466 01 Jablonec nad Nisou
+420 480 023 139, email: ***@***.*** ***@***.***>

www.minion.cz | www.tvorbaloga.cz | www.tvorbainfografiky.cz
www.facebook.com/MinionInteractive
www.twitter.com/minioncz


st 22. 9. 2021 v 18:30 odesílatel Wilco Alsemgeest ***@***.***>
napsal:

**Comment by conconnl** [comment] 2021-09-22 16:38
According to the website older OS do not support it. That is probably the case.

**Comment by pe7er** [comment] 2021-09-22 16:57
No issues on Linux Ubuntu 20.04 in Chrome and FireFox.
All images are visible..

**Comment by brianteeman** [comment] 2021-09-28 12:05
It is super easy to fix by providing a fallback image for those browsers that do not support webp

**Comment by conconnl** [comment] 2021-09-29 21:46
> It is super easy to fix by providing a fallback image for those browsers that do not support webp

Sounds good, where can you configure this in com_content, this part just shows the intro Image selected in the article?
cc @bembelimen

**Comment by brianteeman** [comment] 2021-09-29 21:48
I would help you but I am still waiting a reply on the other issue.

**Comment by TLWebdesign** [comment] 2023-04-17 21:31
This can be closed since last year we switched to svg instead.

**Comment by chmst** [comment] 2023-04-17 21:33
Thanks, closing

**Closed by chmst** 2023-04-17 21:33 UTC
