### ISSUE TITLE
[jshow] Instagram-Logo not shown

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#1002] opened 2017-07-26 06:16 UTC
As Title say:
![bildschirmfoto 2017-07-26 um 08 14 55](https://user-images.githubusercontent.com/8235763/28607143-bc5d35ee-71da-11e7-8475-09e87b34d4ea.jpg)

**Comment by Sandra97** [comment] 2017-07-26 10:03
It's because the template hasn't been updated since April.
Duplicate of #989

**Closed by Sandra97** 2017-07-26 10:03 UTC
