### ISSUE TITLE
Navigation broken link 

### ISSUE THREAD

**Issue by pr410** [joomla/joomla-websites#712] opened 2016-10-15 19:37 UTC
> Please only use this repository to report issues with `*.joomla.org` websites. For bug reports pertaining to the Joomla CMS, please report issues at https://github.com/joomla/joomla-cms/issues/new and for user support issues please post on the Joomla Forum at http://forum.joomla.org. You may remove this section from your issue report.

Please describe the problem or your issue
This what i have come across that under Joomla volunteer page, users are not able to navigate under my profile. It doesn't allow to hoover on it and upon clicking on profile tab, it takes it to Joomlers tab. This error needs to be fixed.
**https://volunteers.joomla.org/joomlers/0-**

**Comment by sanderpotjer** [comment] 2016-10-16 10:09
@pr410 thanks for reporting the issue. The https://volunteers.joomla.org/joomlers/0- page is fixed. I can't duplicate the "users are not able to navigate under my profile." issue. Could you please let me know your username on the Volunteers Portal and the steps to reproduce the issue? Thanks!

**Comment by pr410** [comment] 2016-10-16 16:05
Hi Sander,


There is still error on this page and it doesn't allow it's users to review their profile.

My User Name is: P Rana

[cid:1fea1786-67f2-4bb8-99bf-58cc6a63e288]

Kind Regards

Rana



________________________________

**Comment by sanderpotjer** [comment] 2016-10-16 20:30
@pr410 thanks for the information. It looks like you signed up twice? Do you recall from which location on the site, as there was no volunteer profile created automatically. This was causing the issues for you. This is fixed now and you should be able to edit your profile.

**Comment by Sandra97** [comment] 2016-10-23 12:37
@pr410, could you please confirm your issue is fixed so that we can close it? 
Thank you!

**Comment by pr410** [comment] 2016-10-25 18:23
Hi Joomler,
I was at work, I will go through the home page and let you know.
Many thanks
Rana
Sent from my iPhone

On 23 Oct 2016, at 13:41, Sandra Thevenet <notifications@github.com<mailto:notifications@github.com>> wrote:


@pr410<https://github.com/pr410>, could you please confirm your issue is fixed so that we can close it?
Thank you!

-

**Comment by pr410** [comment] 2016-10-27 20:02
hi Sandra
I have created a new issue for more information. Please have a look. 

Thank you

**Comment by Sandra97** [comment] 2016-10-28 01:50
Hi Rana,
I'm closing this issue here as Sander has moved it to the repository for volunteers.joomla.org: joomla/volunteers.joomla.org#61

**Closed by Sandra97** 2016-10-28 01:50 UTC
Labels: Volunteers, wrong link
