### ISSUE TITLE
hcaptcha

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1559] opened 2020-11-20 12:21 UTC
I was presented with the hcaptcha on the extensions site and it marked as both required and optional

![image](https://user-images.githubusercontent.com/1296369/99799650-eb3a0100-2b2a-11eb-9d7e-4808831c78c3.png)

**Comment by conconnl** [comment] 2020-11-20 12:37
Duplicate of: https://github.com/joomla/joomla-websites/issues/1489

This is a known issue according to the developers repository:
https://github.com/pe7er/hCaptcha/issues/25

It holds explanation that it's a Joomla CMS problem.
I quote:
> hmm seems this is comming from here: https://github.com/joomla/joomla-cms/blob/d3b544e92b04e6421cd683602e6535eb470ba276/components/com_contact/layouts/joomla/form/renderfield.php#L52 I'm not sure how to overcome that other than in a template override.

**Comment by brianteeman** [comment] 2020-11-20 13:20
If its a template and not an extension problem then I guess the ball is in your court to fix it and not Peter


Also on the extensions site on the report an extension page you get another misconfigured instance of hcaptcha

![image](https://user-images.githubusercontent.com/1296369/99804538-11639f00-2b33-11eb-97ab-1fa2cf4b1913.png)

**Comment by conconnl** [comment] 2020-11-20 13:26
Why do you think it’s template, while @zero-24 who knows a lot more about these things provides a link to the CMS code itself. 
He and @pe7er looked at it, because this is / was on every website we checked. 

@anibalsanchez can you look at the other issue mentioned by @brianteeman ?

**Comment by anibalsanchez** [comment] 2020-11-20 13:45
Why the captcha is marked as optional ... it is not obvious to me.

To solve it,  I've just overridden COM_USERS_OPTIONAL with "".

**Comment by brianteeman** [comment] 2020-11-20 13:47
> Why do you think it’s template, while @zero-24 who knows a lot more about these things (then me) provides a link to the CMS code itself.

I said it can be fixed in the template as Peter said. Even if that's not the fix for every website it can be done for this one on the template

I just quickly installed it on one of my test site and the protostar template has this bug but my own template does not because my own template is not using the com_contact renderfield override

**Comment by brianteeman** [comment] 2020-11-20 13:50
Ok I fixed the code. The bug is in hcaptcha and I will submit the PR.

**Comment by conconnl** [comment] 2020-11-20 13:52
Thanks for the additional explanation.
As well for finding a fix, I'm sure Peter will happily add it to a new release.

**Comment by brianteeman** [comment] 2020-11-20 13:52
its such an obvious error that I guess the experts didnt see it

**Comment by brianteeman** [comment] 2020-11-20 14:06
For reference this is the fix

https://github.com/pe7er/hCaptcha/pull/31

**Comment by conconnl** [comment] 2020-11-23 22:43
A new release was done by the developer and installed on the JED.
<img width="511" alt="image" src="https://user-images.githubusercontent.com/11913918/100023672-ac839f80-2de5-11eb-9558-56ee8cc48a21.png">

Thanks @brianteeman & @pe7er

**Closed by conconnl** 2020-11-23 22:43 UTC
