### ISSUE TITLE
[jorg] Feed not found

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#889] opened 2017-03-16 06:50 UTC
![bildschirmfoto 2017-03-16 um 07 49 43](https://cloud.githubusercontent.com/assets/8235763/23985076/416066c4-0a1d-11e7-9ac7-661f3266d8b8.JPG)

**Comment by sanderpotjer** [comment] 2017-03-16 06:59
Looks like they are back:
<img width="1085" alt="screen shot 2017-03-16 at 07 58 10" src="https://cloud.githubusercontent.com/assets/522834/23985267/60273fc8-0a1e-11e7-8e37-0e4f005cc5e7.png">

**Comment by franz-wohlkoenig** [comment] 2017-03-16 07:16
not on my Side. Propably CDN-Issue.

**Comment by Sandra97** [comment] 2017-03-16 10:16
They are displayed for me.
@franz-wohlkoenig Could you tell me if it's ok or not for you?
If yes, please close this issue.
Thank you.

**Comment by jeckodevelopment** [comment] 2017-03-16 10:36
same issue here from Slovakia.

**Comment by Sandra97** [comment] 2017-03-16 10:40
@jeckodevelopment Could you check again now?

**Comment by jeckodevelopment** [comment] 2017-03-16 10:44
it works now, thanks

**Comment by franz-wohlkoenig** [comment] 2017-03-16 10:53
works again.

**Comment by franz-wohlkoenig** [comment] 2017-03-16 11:58
"Feed not found" again.

**Comment by mbabker** [comment] 2017-03-16 12:04
The only thing that's ever a CDN issue is template media, the sites themselves aren't served behind a CDN (architecturally we aren't at a point where this needs to be hooked up).  The feeds do get cached though, the same as all other content on the site.  For whatever reason though, seems that server/site is having a hard time connecting over to the other subdomains to pull the feeds (it's working just fine on the .org sandbox and the sites are obviously online).

**Comment by franz-wohlkoenig** [comment] 2017-03-16 12:23
@mbabker close and no more reporting?

**Comment by Sandra97** [comment] 2017-03-17 18:30
As it seems the feeds are now correctly displayed, I'm closing this issue.
Re-open if needed.

**Comment by sam-suresh** [comment] 2017-03-18 02:28
Feeds not found here from Asia. 
![screen shot 2017-03-18 at 10 27 38 am](https://cloud.githubusercontent.com/assets/5198092/24068269/97231eea-0bc5-11e7-8c82-616c7fd555c5.png)

**Comment by mbabker** [comment] 2017-03-18 03:15
The location does not matter.  The site content itself does not differ based on location nor is it served over a CDN, the only things on the CDN are the base template CSS and a few images.

This issue does not need to be opened and closed every time the "Feed not found." message is displayed.  Either keep it open and someone do a root cause analysis why it is reoccurring or close it and keep it closed (generally clearing the site cache clears the issue, if it doesn't someone needs to get in and debug which isn't the easiest thing since the core feed and HTTP libraries or the `mod_feed` modules don't do any sort of logging on an error state.

**Comment by sam-suresh** [comment] 2017-03-18 03:26
I can see its loading now. 
I agree to keep this open until someone find the cause or it stop occurs.

**Comment by zero-24** [comment] 2017-03-18 03:52
What about adding logging here: https://github.com/joomla/joomla-cms/blob/3.6.5/modules/mod_feed/helper.php#L41 As this are the two places where this is set.

Maybe the expection message can help to understand what is hapening if we write it to a log file?

**Comment by franz-wohlkoenig** [comment] 2017-03-18 10:54
Feed "Developer News" is always found. Whats the Difference to other 3 Feeds?

**Comment by Sandra97** [comment] 2017-03-18 11:10
The 4 feeds are set up in the same way on jorg.

**Comment by mbabker** [comment] 2017-03-18 11:58
The developer subdomain is on a different server than the other two subdomains (www is on yet another server separate from those).

**Comment by Joomv** [comment] 2017-03-18 12:00
Leave it open and I will have a thwack at it over the weekend




On Sat, Mar 18, 2017 at 12:58 PM +0100, "Michael Babker" <notifications@github.com> wrote:












The developer subdomain is on a different server than the other two subdomains (www is on yet another server separate from those).

**Comment by mbabker** [comment] 2017-03-19 17:45
The Exception's message is "SSL connect error".

**Comment by Joomv** [comment] 2017-03-27 19:10
Could everyone who experienced this please check now?  It looks like this has been fixed, but would love more reports from the wild to confirm.  Thanks

**Comment by Sandra97** [comment] 2017-03-27 19:15
I didn't have the issue in the last couple of days.

**Comment by Joomv** [comment] 2017-03-27 19:29
@franz-wohlkoenig @zero-24 @jeckodevelopment @sanderpotjer @sam-suresh 

Could you please let me know too?  I have left the ticket with Rochen open until I have several confirmations.
Thanks

**Comment by sanderpotjer** [comment] 2017-03-27 20:01
@joomv never had the issue, so can't check. Sorry :)

**Comment by sam-suresh** [comment] 2017-03-27 23:04
All loading now

**Comment by franz-wohlkoenig** [comment] 2017-03-28 05:44
in last 3-4 days had it several Times, minimum 1 time a Day. Not now.

**Comment by Joomv** [comment] 2017-03-28 07:19
Thanks everyone.  Going to close this now.

**Closed by Joomv** 2017-03-28 07:19 UTC
