### ISSUE TITLE
[JCM] Uncaught TypeError: a is not a function - jquery.magnific-popup

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-websites#850] opened 2017-02-14 16:19 UTC
Hi,

I've noticed that I can't read the comments in an article.

It seems that there is a Javascript conflict, preventing the load of comments.

jquery.magnific-popup.min.js?v2.7.1:4  - Uncaught TypeError: a is not a function

Uncaught ReferenceError: jQuery is not defined

Checking the scripts that are loaded in the page, it is odd that jQuery is not being loaded before one of its plugins.

My browser: Chrome Version 56.0.2924.87 (64-bit) and Firefox Developer Edition 53.0a2 (2017-02-13) (64-bit)

**Comment by JacquesR** [comment] 2017-02-15 07:04
I have noticed that the comments don't always display, but I'm not sure what the cause is. 

The script error itself is now fixed. There's a K2 param to choose which version of jquery to load. It was set to not load any. When I change it to load jquery the order of the scripts changes and the error is solved.

I'm not sure this relates to the randomly missing comments though?

**Comment by anibalsanchez** [comment] 2017-02-15 09:28
Solved!

Since comments relay on JavaScript, if sometimes they are not loaded, it must be related to a loading conflict.

**Comment by MATsxm** [comment] 2017-03-03 20:44
closing as solved (above)
reopen if needed

**Closed by MATsxm** 2017-03-03 20:44 UTC
Labels: JCM

**Comment by Damaris84** [comment] 2017-10-21 08:37
How exactly did you do it? I have the same problem. It shows "a is not a function"
