### ISSUE TITLE
[jorg] warning on the technical requirements page

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-websites#333] opened 2016-05-14 15:33 UTC
https://www.joomla.org/about-joomla/technical-requirements.html

Access that link
See the warning from the next screenshot:

![wp_ss_20160514_0001](https://cloud.githubusercontent.com/assets/2596554/15269264/bbb0da2c-19f9-11e6-9c6d-390ce26a4170.png)

First report by @BurtNL at https://github.com/joomla/joomla-cms/pull/10446#issuecomment-219108807

**Comment by MATsxm** [comment] 2016-05-14 16:05
unable to reproduce

**Comment by MATsxm** [comment] 2016-05-14 16:12
ok, got it as the link in `installation/INSTALL` is https://www.joomla.org/technical-requirements.html and not: https://www.joomla.org/about-joomla/technical-requirements.html
@Sandra97 a redirection?

**Comment by Sandra97** [comment] 2016-05-14 16:27
Issue solved. The redirection was not correct.
Closing the issue.
Re-open if needed.

**Closed** 2016-05-14 16:29 UTC
Labels: .org, wrong link

**Comment by zero-24** [comment] 2016-05-14 17:11
Thanks i did not get that is was the wrong link.

**Comment by zero-24** [comment] 2016-05-14 18:13
@Sandra97 can you please double check? If i access this link: https://www.joomla.org/technical-requirements.html i still get the warning.

**Comment by brianteeman** [comment] 2016-05-14 18:15
Me too

On 14 May 2016 at 19:13, zero-24 <notifications@github.com> wrote:

> @Sandra97 <https://github.com/Sandra97> can you please double check? If i
> access this link: https://www.joomla.org/technical-requirements.html i
> still get the warning.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/333#issuecomment-219234942>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Sandra97** [comment] 2016-05-14 18:22
I checked more than 10 times. 
On Firefox, no warning. 
On Edge, warning the 1st time. Then, no more warning.
On Chrome, the warning is displayed, even after several tests.
Can it be a cache issue?

**Comment by Sandra97** [comment] 2016-05-14 18:26
Note we are talking about an issue on a page that nobody is supposed to visit:  https://www.joomla.org/technical-requirements.html, as it does not exist in Google, Yahoo, Bing.

**Comment by MATsxm** [comment] 2016-05-14 18:27
ahaha
But Brian decided this page does/should stay like it is

**Comment by brianteeman** [comment] 2016-05-14 18:27
I get the warning on firefox
http://i.tee.mn/1RUQ.png

On 14 May 2016 at 19:22, Sandra97 <notifications@github.com> wrote:

> I checked more than 10 times.
> On Firefox, no warning.
> On Edge, warning the 1st time. Then, no more warning.
> On Chrome, the warning is displayed, even after several tests.
> Can it be a cache issue?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-websites/issues/333#issuecomment-219235396>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Sandra97** [comment] 2016-05-14 18:28
I don't 
![1](https://cloud.githubusercontent.com/assets/4682328/15270043/2e620736-19e0-11e6-9cb4-2794f32eb924.png)

**Comment by mbabker** [comment] 2016-05-14 18:29
Originally the page wasn't in the /about menu.  We moved it when we did the
update, I don't remember why anymore though.  The redirect works fine
except for some random Joomla error.
