### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by JanHeijboer** [joomla/joomla-websites#1371] opened 2019-11-06 20:49 UTC
When you opens a article in joomla 3.9.13 and than save as copy the new article is empty...

**Comment by Sandra97** [comment] 2019-11-06 21:02
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS. If you find a bug in Joomla CMS, please report it at issues.joomla.org

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

**Note: I can't reproduce your issue, it works as expected for me**

Thanks!

**Closed by Sandra97** 2019-11-06 21:02 UTC
