### ISSUE TITLE
Modify the Configuring_a_XAMPP_server_for_joomla_development as it has the older version of xampp[jdocs] 

### ISSUE THREAD

**Issue by manav014** [joomla/joomla-websites#1384] opened 2020-02-09 20:59 UTC
The latest version of Joomla as per today is 3.9 that supports php7. But in the https://docs.joomla.org/Configuring_a_XAMPP_server_for_joomla_development tutorial, the xampp version which is mentioned is 1.7.7 which support php5 or less. And also the version of xdebug mentioned in the tutorial does not support PHP 7. And while configuring I faced a lot of problems due to such mismatching of versions. So, there is a need to modify the tutorial as per the latest version of xampp, xdebug and Joomla.

I can handle the issue but don't have reference to the source code.

**Comment by pe7er** [comment] 2020-02-18 14:57
Thanks for reporting the issue with the documentation.
The documentation website is a wiki which means that anybody could help to improve it.

Good to hear that you've handled the issue with mismatching versions yourself!
Could you please update the documentation with your findings?
That would be very helpful for other Joomla users!
Thanks!

**Comment by manav014** [comment] 2020-02-19 03:37
Actually I am don't have any code pointers with me and even I was unable to get the GitHub repository link of the same. I could solve the issue if I could get some references to the code or some code pointers or maybe a link to the GitHub repository of the same.

**Comment by pe7er** [comment] 2020-03-23 13:18
@conconnl Sorry, I'm using my own LAMP stack and I have no recent experience with XAMPP.

**Comment by conconnl** [comment] 2020-03-23 13:57
I understood that the requester wanted to update the docs but needed help. If I miss understood and the issue is solved / finished, we should close it.

**Comment by hvdmeer** [comment] 2020-03-23 14:49
This doc is pretty outdated and I'm not sure if all information there should be on it. "Problem" is that it contains specific Apple, Linux and Windows instructions and most people don't use more than one. (I said most!)

I can share this issue at the "JDocs Translations WG" on Glip.

**Comment by conconnl** [comment] 2020-03-23 15:15
Please do, I would think we don’t write the documentation ourselves, but clearly link to the explanation of the creators themselves with possibly some joomla specific information added. 
This way you don’t have to maintain it and still help people finding the correct info.

**Comment by hvdmeer** [comment] 2020-03-23 15:20
Posted in that channel

**Comment by slibbe** [comment] 2020-03-23 22:59
I will have a look. I have used XAMPP in the past and can install it again on Windows and Linux.

**Comment by coolwebcreations** [comment] 2020-04-15 22:08
Now we have a new XAMPP page at JDocs thanks to @wilsonge . All old XAMPP pages should now redirect to this page: https://docs.joomla.org/XAMPP
Issue solved

**Closed** 2020-04-15 23:21 UTC
Labels: Documentation

**Comment by wilsonge** [comment] 2020-04-15 23:23
Thanks! But credit actually to @softforge for Writing the tutorial :)

**Comment by pe7er** [comment] 2020-04-16 06:45
Thanks Phil @softforge !
