### ISSUE TITLE
[jorg] SEO Result for Joomla Download

### ISSUE THREAD

**Issue by pbwebdev** [joomla/joomla-websites#219] opened 2016-02-09 22:28 UTC
This one is for someone that can manage the Google Links.

Search for the term "Joomla Download"
![screen shot 2016-02-10 at 9 24 23 am](https://cloud.githubusercontent.com/assets/3688954/12932735/628b02f8-cfd8-11e5-91b8-53d27bc08224.png)

The links below takes you to
https://www.joomla.org/download.html?tmpl=component

Needs a 301 htaccess rule to redirect ?tmpl=component references to not have it.
also needs to be removed from visible links in Google Search Console.

Most likely a task for Ruth and someone good at regex.

**Comment by mbabker** [comment] 2016-03-02 14:15
`?tmpl=component` shouldn't be blindly redirected as it has legitimate use cases in Joomla.  But yes the search index data should be updated.

**Comment by MATsxm** [comment] 2016-04-22 19:50
Closing as a duplicate of #300

**Closed by MATsxm** 2016-04-22 19:50 UTC
Labels: .org, SEO/SEF
