### ISSUE TITLE
[jhelp] "RuntimeException" at different Help-Sites [3.7]

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#827] opened 2017-01-14 11:46 UTC
Got at "https://help.joomla.org/proxy?keyref=Help37:JHELP_COMPONENTS_com_patchtester_OPTIONS&lang=en"
`RuntimeException
Error fetching page from MediaWiki API: The page you specified doesn't exist`

#### Using:

Joomla! 3.7.0-alpha2-nightly
macOS Sierra, 10.12.2
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by zero-24** [comment] 2017-01-14 12:51
IIRC there is no help page for the patchtester?

**Comment by franz-wohlkoenig** [comment] 2017-01-14 13:03
Patchtester was an example, got same error on other examples:
https://help.joomla.org/proxy?keyref=Help37:Components_Article_Manager_Options&lang=en
/administrator/index.php?option=com_admin&view=help
https://help.joomla.org/proxy?keyref=Help37:Components_Tags_Manager&lang=en

**Comment by MATsxm** [comment] 2017-01-14 13:11
Strange thing is that the URL are not the good ones:
https://help.joomla.org/proxy?keyref=Help37:Components_Tags_Manager&lang=en
should be
https://help.joomla.org/proxy?keyref=Help36:Components_Tags_Manager
instead (namespace 36 and without the lang as this page is not yet available for t9n)

**Comment by MATsxm** [comment] 2017-01-14 14:12
also, it looks to work here for example for the Tags Manager helpScreen???
![e09231b8e8d876c74ce4ca5bbb70361c](https://cloud.githubusercontent.com/assets/1972717/21955454/dfa530be-da41-11e6-87c1-c2a3bf00797b.png)

**Comment by MATsxm** [comment] 2017-01-14 14:22
@franz-wohlkoenig are you trying to reach the HelpScreens from a Dev version or the latest stable one?

**Comment by MATsxm** [comment] 2017-01-14 14:24
oh boy... my bad I haven't read your info....
then closing as not a bug and expected behavior.
The nameSpace 3.7 on the Doc/Help will be created as soon as the stable 3.7 will be available.

**Closed by MATsxm** 2017-01-14 14:24 UTC

**Comment by franz-wohlkoenig** [comment] 2017-01-14 14:57
@MATsxm thanks for evaluating that this is not a bug.
