### ISSUE TITLE
[jrescs] Login page can't be found

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-websites#403] opened 2016-07-11 20:32 UTC
I'm trying to log in.  It's not saying that I have failed, it is saying the page cannot be found.  I probably am failing to log in I suppose, if so that is unclear, if I am logging in correctly then I think a redirect is broken.

I am trying to login via the sidebar login on this page.  http://resources.joomla.org/en/jrd-news

**Comment by genr8r** [comment] 2016-07-11 20:36
hmmm.  My login takes me to here... http://resources.joomla.org/en/manage-listings

which is our preferred behavior as we want to make it easy for registrants to submit their proposals.  I am going to try registering with a fresh account to make sure it isn't an ACL issue.

**Comment by genr8r** [comment] 2016-07-11 20:41
I can't reproduce the issue even with a simple "registered" user??? I am logging in with 3 different accounts.  One of them is a newly registered account, another older "registered" account I keep for testing, and my admin account. No problems on any of the three. I am using the sidebar login from the page that you referenced.  If you have more detail about how you are getting the error, please let me know.

**Comment by brianteeman** [comment] 2016-07-11 20:43
Not only does it say page not found but there is an error

 0 Cannot open file for writing log

**Comment by genr8r** [comment] 2016-07-11 21:27
??? Cleared site and local cache. Trying plain registered user accts on chrome and FF on OSX. Still can't recreate the problem. Fired it up with and without https.  Any insight on what I am missing? I will drop a note to the rest of the JRD team to see if one of them can reproduce/resolve the item.

**Comment by brianteeman** [comment] 2016-07-11 21:31
Try a non existent user ie one that will fail

**Comment by genr8r** [comment] 2016-07-11 21:34
We have a winner. I misunderstood the original post as a login problem. I can chase it down now.

**Comment by brianteeman** [comment] 2016-07-11 21:36
Well it is a login problem as
1. It's not redirecting to a page with the login failed message
2. The log file isn't writeable

**Comment by genr8r** [comment] 2016-07-12 17:01
Hi @brianteeman please pardon my lack of clarity. I meant that I initially understood this as an issue with the successful login redirect rather than the failed login redirect. I should have read the first post more carefully. You are correct semantically speaking, that these are both a subset of login problems.

Turns out even after setting proper permissions AND trying to force the correct ownership on the log directory (the log is "writable") admintools is still not able to write the security exception of a bad login. We got it figured out.

I want to thank Saeed (https://volunteers.joomla.org/joomlers/saeed-gh) for taking the lead on resolving this item.

**Closed by genr8r** 2016-07-12 17:01 UTC
Labels: Login, Resources

**Comment by uglyeoin** [comment] 2016-07-13 11:22
Good work Saeed
