### ISSUE TITLE
[jrepo] announcements way to big ... 

### ISSUE THREAD

**Issue by mikeveeckmans** [joomla/joomla-websites#96] opened 2015-08-30 20:12 UTC
The joomla announcements part is way to big, can we shorten either the posts with a read more after the first paragraph or just show first lines of text? 
http://www.screencast.com/t/PKfAe7aua

**Comment by mbabker** [comment] 2015-08-30 20:15
The current site uses a custom layout to truncate the text.  With the readmore right after the first paragraph there's next to no text on the page under the graphic.

**Comment by MAT978** [comment] 2015-08-30 20:21
the cleanup was TOO clean :stuck_out_tongue_winking_eye: 
Back to normal then - closed

**Comment by mbabker** [comment] 2015-08-30 20:25
IMO we need the layout override back from the 2.5 site to truncate the article text and the readmore moved back down.  Otherwise http://repository.joomla.org/announcements/release-news.html looks pretty bad with a single line of text that barely stands out under the massively large graphic.

**Comment by mikeveeckmans** [comment] 2015-08-30 20:34
@mbabker can you help us out with the override ?

**Comment by mbabker** [comment] 2015-08-30 20:41
Done.  Just needs a `div.newsflash-body { margin-bottom: 10px; }` CSS rule to move the Read More link down a little bit.

**Comment by mikeveeckmans** [comment] 2015-08-30 20:42
Awesome, thank you !

**Comment by MAT978** [comment] 2015-08-30 20:50
Ouch!
have you had a look at the HP @Sandra97

**Comment by Sandra97** [comment] 2015-08-30 21:12
It's ok now.

**Comment by Hutchy68** [comment] 2015-08-30 21:14
News page (http://repository.joomla.org/announcements/release-news.html)

>Otherwise http://repository.joomla.org/announcements/release-news.html looks pretty bad with a single line of text that barely stands out under the massively large graphic.

It would be easy to css the images to float smaller to the right, then center max-width on smaller screens. Unfortunately, some of the images are style="max-width:100%" hard coded.

![image](https://cloud.githubusercontent.com/assets/3527469/9569440/a141eafe-4f39-11e5-81cf-c1313390f46a.png)

![image](https://cloud.githubusercontent.com/assets/3527469/9569446/bc41d8a0-4f39-11e5-873c-928e6175913d.png)

to tablet size

![image](https://cloud.githubusercontent.com/assets/3527469/9569462/33eb8cac-4f3a-11e5-91e1-cae3e9ad3fe0.png)

and then mobile

![image](https://cloud.githubusercontent.com/assets/3527469/9569467/5fffd21c-4f3a-11e5-9cf6-c02bdbbe71ac.png)

**Comment by Sandra97** [comment] 2015-08-30 21:23
I so much agree with you Tom. I can override the inline style but it won't be in a "clean" way .
The problem is that the images have not been added in the best way: by using the image tabs...
And it's a work for phase 2.

**Comment by mbabker** [comment] 2015-08-30 21:29
Some of the images are inline with the article and some in the tabs.  If I
published it assume the image options in the tabs were never used unless
someone is cleaning up after me.

**Comment by MAT978** [comment] 2015-08-30 21:33
Phase 2

**Comment by Hutchy68** [comment] 2015-08-30 21:39
Ok, put it on Phase 2 list. Closing

**Closed by Hutchy68** 2015-08-30 21:39 UTC
Labels: content, repoSite
