### ISSUE TITLE
[volunteers.joomla.org] Search-Module messing Site

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-websites#841] opened 2017-02-06 18:52 UTC
On smaller Screensizes Searchbox-width is messing site:
![bildschirmfoto 2017-02-06 um 19 45 46](https://cloud.githubusercontent.com/assets/8235763/22661482/c722be64-eca5-11e6-86ec-3a423be44f39.png)

**Comment by mbabker** [comment] 2017-02-06 19:08
1) Why does mod_search not have the `input-medium` class on its input the same way the mod_finder input does?  (This is why the search input is longer on this site than www.joomla.org as an example)

2) We have a template issue in general with that search box, it's not unique to the volunteer portal (except for the fact that it uses a different search component with a different output because core inconsistencies rule).  On the other sites it drops to two lines between 980px and 985px too, part of the problem is the menu is now longer than when it was originally designed and with some sites now being localized some languages have the problem worse than others (it's why we just hide the search for the 768px through 979px viewport now).

**Comment by sanderpotjer** [comment] 2017-02-15 22:29
Fixed with a template override for mod_search. But should be corrected in the core of course :) So created PR: https://github.com/joomla/joomla-cms/pull/14099

**Closed by sanderpotjer** 2017-02-15 22:29 UTC
Labels: responsive, Volunteers
