### ISSUE TITLE
[jcomm]  Joomla! Shop checkout issues

### ISSUE THREAD

**Issue by Didldu-Florian** [joomla/joomla-websites#655] opened 2016-09-27 09:41 UTC
https://community.joomla.org/the-joomla-shop.html

Seems there´s a problem on Joomla! Shop checkout page. I did taken the order twice, 
because after first I couldn´t find any option to pay my order. Not sure why, but on second try it did worked.

On Joomla! Germany facebook group also another user had  the same problem.
Best regarsd, Florian

**Comment by mikeveeckmans** [comment] 2016-09-27 10:31
Shared with hika

**Comment by hikashop-nicolas** [comment] 2016-09-27 10:42
Hi,

I'm not able to reproduce the problem. Please provide instructions to reproduce the issue.

**Comment by Didldu-Florian** [comment] 2016-09-27 11:11
On first order it was completed without any pay option. Perhaps i have overlooked something.
Tahn it could be a usability problem. On second order I was able to select paypal and to checkout.

**Comment by mikeveeckmans** [comment] 2016-09-27 11:19
Closing this, reopen if needed

**Closed** 2016-09-27 11:25 UTC
Labels: bug, Shop
