### ISSUE TITLE
[josm] Obsolete links / 404 Links

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#383] opened 2016-06-17 00:48 UTC
Page: http://opensourcematters.org/joomla/the-joomla-community.html 

News portal link - `http://news.joomla.org `(I guess that this website no longer exists).

`please submit your short story, article, announcement or review`... links to 
`https://www.joomla.org/component/option,com_submissions/Itemid,75` and it's a 404

**Comment by jeckodevelopment** [comment] 2016-06-17 13:05
@marijkestuivenberg can you look at this?

**Comment by Sandra97** [comment] 2016-06-26 10:29
Closing this issue as it's a duplicate of #132

**Closed by Sandra97** 2016-06-26 10:29 UTC
Labels: content, OSM, wrong link
