### ISSUE TITLE
[jissues] requires inappropriately broad permissions on github

### ISSUE THREAD

**Issue by jepler** [joomla/joomla-websites#441] opened 2016-08-04 14:20 UTC
I began the process of filing an issue on the joomla issue tracker (https://issues.joomla.org/), which requested that I "Login with GitHub".  The permissions requested by the tracker on github are inappropriately broad: 

> This application will be able to read and write all public repository data. This includes the following:
> -    Code
> -    Issues
> -    Pull requests
> -    Wikis
> -    Settings
> -    Webhooks and services
> -    Deploy keys

![Inappropriate permissions](https://cloud.githubusercontent.com/assets/1517291/17405302/9cdd0c9a-5a24-11e6-9889-17327e63d574.png)

**Comment by mbabker** [comment] 2016-08-04 14:40
Unless I'm missing something obvious there isn't a way to configure the application's scopes via GitHub.  Even with the broadness of it, at most all that is happening is creating issues and comments on your behalf.  We aren't storing tokens in any way that allows us to do anything else, the OAuth token is stored to your session.

**Comment by jeckodevelopment** [comment] 2016-08-04 17:01
@jepler , if you don't want to gran permission to JTracker, you can submit your issue just using the GitHub web interface (in the same way you did with this issue).

**Comment by mbabker** [comment] 2016-08-04 17:22
I've gone through https://developer.github.com/v3/oauth/#scopes and the way I'm reading the scopes we need the `public_repo` permission which grants all of the above permission.  This is because items submitted on the issue tracker are published via GitHub's API acting as your account using the OAuth token we have been authorized for that session.  There is not a scope that is more limited to only the write actions we are taking, which as noted above is creating issues and comments.  I'm sorry there is nothing more I can do here.

Closing as expected behavior.  I would suggest contacting GitHub to see if they would be willing to introduce more scope levels to the OAuth workflow.

**Comment by jepler** [comment] 2016-08-04 22:18
Thanks for looking into it.

**Comment by mbabker** [comment] 2016-09-14 18:51
After [today's Integrations announcement](https://developer.github.com/changes/2016-09-14-Integrations-Early-Access/) it will be possible in the future to do something about this.  Re-opening this to keep it visible.  It'll probably be some time before we're able to do something with this but it should now be possible to re-adjust how the issue tracker integrates with GitHub user accounts.

**Comment by jeckodevelopment** [comment] 2016-09-14 20:06
thank you Michael

**Comment by MATsxm** [comment] 2016-11-20 11:45
following @mbabker closing this issue
re-open if needed

**Closed by MATsxm** 2016-11-20 11:45 UTC
Labels: Issue Tracker, Login
