### ISSUE TITLE
[joomla.org] 

### ISSUE THREAD

**Issue by thinkerytim** [joomla/joomla-websites#1279] opened 2019-01-03 05:26 UTC
attempting to launch a new Joomla 4 alpha site fails when using an existing account-- it says the password is wrong (despite having verified the password on cloudaccess.net several times)

**Comment by jonathanCA** [comment] 2019-01-03 14:21
Hi Tim, thank you for reporting this to us, we will investigate immediately. We've attempted to look up the site you are referring, but we were unable. I'll reach out to you directly, then report back here once we have identified the cause/solution.

**Comment by jonathanCA** [comment] 2019-01-10 15:04
Following up here - we've identified the problem, which is now solved. The issue was isolated to the site involved in this case. 

We can close this issue. Thanks again for reporting.

**Closed** 2019-01-10 15:05 UTC
Labels: launch
