### ISSUE TITLE
[jshow] Can't browse categories

### ISSUE THREAD

**Issue by jeckodevelopment** [joomla/joomla-websites#1011] opened 2017-08-13 16:35 UTC
In the showcase homepage, browsing by category is not possible.

![image](https://user-images.githubusercontent.com/733133/29251517-1d10ecee-8056-11e7-8bfe-318d283f7c1b.png)

No active links in the categories list.

**Comment by mbabker** [comment] 2017-08-13 16:45
Duplicate of #1008

**Closed by mbabker** 2017-08-13 16:45 UTC
Labels: bug, Showcase
