### ISSUE TITLE
[jhelp] 

### ISSUE THREAD

**Issue by AboutTimeIT** [joomla/joomla-websites#1712] opened 2022-01-19 10:25 UTC
Update Joomla! 4.0.5 to 4.0.6 gives error
404 - RuntimeException

Error fetching page from MediaWiki API: The page you specified doesn't exist
License: Joomla! Electronic Documentation License
Copyright © 2022 Open Source Matters, Inc. All rights reserved.
Report an Issue with the help screens

Language file was updated first (no other updates available)
Disabled the Akeeba Backup and tried again --> failed

**Comment by pe7er** [comment] 2022-01-19 10:40
Hi,

This repository is ONLY for reporting issues with the *.joomla.org websites, not about the Joomla! CMS.

For user support issues, please go to:
-https://forum.joomla.org/
-https://docs.joomla.org/Main_Page
-or find a service provider at https://resources.joomla.org/

For this reason, I'm closing your issue here.

Thanks!

**Comment by zero-24** [comment] 2022-01-19 10:58
@pe7er here this could be an issue on the docs / help site not sure who best to ask maybe @coolwebcreations ?

**Comment by pe7er** [comment] 2022-01-19 11:10
Ok, in that case I'll reopen this issue...

**Comment by zero-24** [comment] 2022-01-19 11:17
@AboutTimeIT where in detail do you get this error message can you show us a Screenshot?

**Comment by AboutTimeIT** [comment] 2022-01-19 12:09
![00-administrator_index php_option=com_instal](https://user-images.githubusercontent.com/19489690/150126346-59a5b244-cfd8-44d2-8302-bb9cf9340c8f.jpg)
![01-administrator_index php_option=com_joomlau](https://user-images.githubusercontent.com/19489690/150126379-c70b9986-d7cb-44f3-849b-943cb7143d23.jpg)
![02-administrator_index php_option=com_joomlaupdate](https://user-images.githubusercontent.com/19489690/150126406-f6b37062-89e9-4c81-88a7-f3ef2cd3794e.jpg)

@pe7er If not posted on the correct place then the link might be not correct?

@zero-24 The error occurs directly after starting the update (see screenshot)
I even checked the database and performed an update again --> failed with same error

**Comment by zero-24** [comment] 2022-01-19 12:26
Interesting yes we are aware of time out issues please go to the downloads portal yourself Download the update and upload it via the joomla.

A patch has been prepared here too: https://github.com/joomla/joomla-cms/pull/36742 it looks like the underlying AWS site is slow when reaching it from your server.

**Comment by zero-24** [comment] 2022-01-19 12:27
But where did you got that help page error?

**Comment by zero-24** [comment] 2022-01-23 16:12
Hmm that page: https://help.joomla.org/proxy?keyref=Help40:JHELP_COMPONENTS_JOOMLA_UPDATE&lang=nl loads for me: 
![image](https://user-images.githubusercontent.com/2596554/150687506-f79a9533-c88f-4cca-9bbb-afa9eb5a2831.png)

So I do not get the error message from above.

**Comment by HLeithner** [comment] 2022-08-17 07:50
Is this still relevant or can it be closed @AboutTimeIT @zero-24

**Comment by zero-24** [comment] 2022-08-17 09:54
I would say it can be closed as i can not reproduce the issue as mentiond above.

**Closed** 2022-08-17 10:57 UTC
