### ISSUE TITLE
launch.joomla.org -multiple issues

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-websites#1170] opened 2018-06-13 11:50 UTC
extra word in the footer
Launch.joomla.org is a free website service **is** provided to the general public by CloudAccess.net,

terms of service link goes to borked page with no css or js
https://launch.joomla.org/index.php/terms-of-service

Launch.joomla.org -How it works?
Find out more link goes to a cloudaccess.net pricing page

When you try to launch a new site you are asked for a cloudaccess password

**Comment by Sandra97** [comment] 2018-06-13 15:23
Thanks Brian. I just reported all that to the CA team.

**Comment by jonathanCA** [comment] 2018-06-13 15:29
@brianteeman thank you for the feedback, the wording and links will be fixed immediately

jeckodevelopment is right, the  password prompt comes up if an email address is used which already has an account. We will take the opportunity to make this more clear as well. 

Thanks everyone!

**Comment by brianteeman** [comment] 2018-06-13 15:31
An account where? To the best of my knowledge I don't have an account with cloudaccess

**Comment by Sandra97** [comment] 2018-06-13 15:34
But you may have had an account to the previous joomla.com platform and had received an email with 3 options

**Comment by brianteeman** [comment] 2018-06-13 15:36
Yes I did have one of those but you wouldn't know the password. If that's the reason for this message then it needs massively rewriting

**Comment by jonathanCA** [comment] 2018-06-13 15:57
The password prompt is for people who already have a CloudAccess.net account with the email address used during the launch. We are updating the text to make this a bit more clear, and adding a forgot password section. 

@brianteeman please message me the email address that you used and I'll confirm.. probably you had launched a test account many years ago. We'll gladly remove the data if you would like :)

**Comment by brianteeman** [comment] 2018-06-13 18:06
i guess it must be an old ca account. as i was able to register with a disposable account.
After which I was taken to https://launch.joomla.org/thanks.html# 

This page is broken - the dropdown menus dont work


```
template.min.js?v=28052018:4te  Uncaught TypeError: t.element.dropdown is not a function
    at HTMLAnchorElement.<anonymous> (template.min.js?v=28052018:4)
    at HTMLAnchorElement.handle (jquery.min.js?9f50f1…c7f5199877b265891:3)
    at HTMLAnchorElement.dispatch (jquery.min.js?9f50f1…c7f5199877b265891:3)
    at HTMLAnchorElement.r.handle (jquery.min.js?9f50f1…c7f5199877b265891:3)
```

**Comment by jonathanCA** [comment] 2018-06-13 18:10
Nice catch Brian, our team will get the thanks.html page menu resolved ASAP

**Comment by brianteeman** [comment] 2018-06-13 18:17
You might want to block some potentially embarrassing subdomain s as well. They were blocked on the old system but as you will see I just claimed one that's nsfw

**Comment by jonathanCA** [comment] 2018-06-13 18:22
Yes, we have a blacklist for our other subdomains, this can be applied to joomla.com as well. Task posted 👍

**Comment by brianteeman** [comment] 2018-06-15 14:38
Today I got 4 emails for the joomla.com sites that have been transferred from SG. It is the same email as if I had signed up today. Perhaps it would be better if it stated something about it being transferred from sg

none of the option 1 joomla logins work

no idea what the username and password is for the option 2 ccp login would be

thought it would probably be related to the email address that I received the notifications at but when I tried that email address in the forgot password box it said that the email address was not recognised.

**Comment by jonathanCA** [comment] 2018-06-15 14:54
Thank you Brian - there is a subsequent email you will receive (or maybe already have) that outlines this. I agree the workflow can be improved, we are looking at it closely as migrations continue.

**Comment by jonathanCA** [comment] 2018-06-15 15:05
I've confirmed with our team, the "Welcome to CloudAccess.net (siteground import)" notification is only going to people who do not already have an account with us. Your primary email has an account from long ago. Still, we think it will confuse others as well, so we are updating the logic.

**Comment by brianteeman** [comment] 2018-06-15 15:23
Doesn't address the login issues though

**Comment by jonathanCA** [comment] 2018-06-15 17:13
Thanks Brian, logins are all fully functional. We have also revised the message to existing clients to make sure they are crystal clear. 

We really appreciate your feedback here!.. remind me to loop you into future product releases ;-)

**Comment by brianteeman** [comment] 2018-06-17 12:08
The joomla login details in the email are now working

I havent received any "existing client" email 

I still can't login to the ccp as i dont know the password and the forgotten password function doesnt work as it is says "No client account was found with the email address you entered"

**Comment by ot2sen** [comment] 2018-06-20 14:58
@jonathanCA  couldn´t find where to report issues so adding to this open one.
Tried creating a site about 3 hours ago and haven´t received any mail for confirmation yet

**Comment by jonathanCA** [comment] 2018-06-20 18:07
Hi! Yes this is a good place to post :)  Could you message your email address to us? I will have our team track it.  FWIW, we have not seen any gaps or problems with provisioning that would explain the issue you are seeing, so it's likely an email delivery problem.

**Comment by ot2sen** [comment] 2018-06-20 18:43
Message sent with details of email, server chosen and subdomian chosen to your contact here.

**Comment by jonathanCA** [comment] 2018-06-20 19:42
Thank you Ole, we are looking into it now. I did a quick check and I see your account was created, our Platform Team will review the case and I'll update you via email.

**Comment by wojsmol** [comment] 2018-06-26 22:02
Hi
@jonathanCA Please see issue https://github.com/joomla/joomla-cms/issues/20880 and assist if passible.

**Comment by wojsmol** [comment] 2018-07-01 05:02
@jonathanCA On `Oops, something went wrong... please check back in a bit.`  error page link to CCP in last paragraph has badly quoted href attribute 
````HTML
If you continue to see this error message please submit a support ticket in your <a href="”https://ccp.cloudaccess.net/clientarea.php”">Cloud Control Panel</a> and the CloudAccess.net Team would be happy to help.
````

**Comment by jonathanCA** [comment] 2018-07-01 12:20
Thank you, I will have out team look into this. Feedback is greatly appreciated!

**Comment by wojsmol** [comment] 2018-07-15 17:54
@jonathanCA I created a free account with Joomla! 4.0 alpha pre-installed via advanced options on launch.joomla.org, below are issues i notes:
1. No password to ccp was provident in any mail - resolved by reseating the password via email.
2. Login to Joomla! install not working from ccp with error:

> Error
> Data collection error. Please contact Support

I submitet the ticket and IMHO CA support team is not properly inform about launch.joomla.org - details can be see in CA ticket system for domain with my github login. Now I waiting to check the CA policy for **manually installed** Joomla! 4.0 alpha.
Please assist.

**Comment by jonathanCA** [comment] 2018-07-16 14:07
Hi Wojciech, thank you for bringing these concerns to our attention. See our inline comments: 

1. No password to ccp was provident in any mail - resolved by reseating the password via email.
<<<The way it is currently setup is, immediately after clicking the email verification link, new account holders are prompted to create a password for CCP (screenshot https://www.screencast.com/t/fLm0QjQj ). We don't email the full login details after that for security reasons. 

2. Login to Joomla! install not working from ccp with error: Data collection error. Please contact Support
<<<This is a tricky issue. With the nightly builds of Joomla 4, we aren't able to provide some CCP functionality. This is due to the fact that the Joomla codebase changes on a nightly basis.  The best solution here is more transparency for users. When selecting the "Login" button in CCP, a message needs to come up stating "Auto-login not available for this version of Joomla, please refer to email for instructions on how to log in manually." There are better solutions, but this is something we can put in place immediately to avoid any future confusion. 

3. Regarding our support team, I do see that they provided incorrect information to you in the ticket. We will use this as a chance to improve their knowledge and processes. 

Thanks again - and if you see any further issues or improvements, don't hesitate to post them. Our goal here is a completely seamless system that is used by all.. constant improvement is how we get there 👍

**Comment by jonathanCA** [comment] 2018-08-27 13:51
Just following up, I think we can close this as corrective action had been taken on reported issues and the migration has long since been completed.

**Closed** 2018-08-27 14:41 UTC
Labels: launch
