### ISSUE TITLE
Error codes page link for the JED currently returns a blank page

### ISSUE THREAD

**Issue by genr8r** [joomla/joomla-websites#1785] opened 2022-07-06 18:00 UTC
This page - https://extensions.joomla.org/extension/directory-a-documentation/faq/freestyle-faqs/

...has a link "View Error Codes" that is currently returning a blank page for me at...

https://extensions.joomla.org/support/knowledgebase/item/unpublished-extensions-error-codes/

**Comment by HLeithner** [comment] 2023-10-31 08:35
closing since it's a duplicate of https://github.com/joomla/joomla-websites/issues/1714

**Closed by HLeithner** 2023-10-31 08:35 UTC
Labels: JED
