### ISSUE TITLE
[jrd] Profil Link not Working

### ISSUE THREAD

**Issue by The-Web-Designer** [joomla/joomla-websites#1092] opened 2017-12-04 13:07 UTC
Hi

Already since a few weeks (since October 2017) I have an open ticket, which my JRD profile is no longer publicly accessible.

Can someone take a look at what the problem is?

LINK: https://resources.joomla.org/en/?option=com_rsticketspro&view=ticket&id=1149:jrd-link-ist-not-working&Itemid=577 

_

> Hello
> 
> I have registered in the JRD, unfortunately, the link does not work:
> 
> <a href="https://resources.joomla.org/index.php?option=com_zoo&task=item&item_id=891"> <img src = "https://cdn.joomla.org/jrd/badge-2-3 .png "/> </a>
> Can you see why this is not possible?
> 
>  
> 
> Thanks
> 
>  
> 
> Thomas

_

Thanks!

**Comment by genr8r** [comment] 2017-12-04 18:00
Dupe of the reply just posted via the JRD ticket system...

Hi Thomas,
I am sorry I missed this ticket. Can you please double check the URL that you pasted into your site?
The version that you have included with this ticket has a space right before the ".png" That space would break the link the badge image.
Please let me know if you need further assistance.
Thanks,
 
Brian
Joomla Resources Directory (JRD) volunteer

**Closed by genr8r** 2017-12-04 18:00 UTC
Labels: JRD

**Comment by The-Web-Designer** [comment] 2017-12-12 13:22
Thank you for the info.

I have now worked on this as desired, could you unlock it now?!

thank you
